### ISSUE TITLE
resets each launch

### ISSUE THREAD

**Issue by blammymatazz** [Rash-in/StarParseLinux#10]
I've only been using this for a day and it works really well, except for 1 thing. The starparse settings reset on each launch. I have to re-choose the combat log folders, enter raid team info, change overlay locations/size/etc every time i close and re-open starparse. Did I miss a step somewhere?

**Comment by Rash-in** [comment]
I never ran into this so the instructions never made it into the doc. However, I believe that I know where the problem is.  If you are able to open the app and it parses, then the app are trying to write files but unable to due to permissions.

Below will change the permissions to everything in the .StarParse folder.
Try this:
get your username from terminal: `id`

change the <user> in the below command to what you got back from id. (Make sure the colon stays between the two)
-R is recursive so it nabs all the files and folders


`chown -R  user:user ~/.StarParse/*`

If you get a message saying that you don't have the permissions, put `sudo` before the above command (probably the reason for the permissions issue)

Lemme know if that works. Can add to the doc if it does. 

FYI:
The files that are not able to be read from/written to:
- ~/.StarParse/StarParse/app/client/app:
- - starparse.xml      <-----the one pointing to logs directory
- - starparse-attacks.xml
- - starparse-timers.xml

**Comment by blammymatazz** [comment]
I followed your suggestions, but I'm not sure if it changed anything. I managed to save all my raid info by opening starparse with the game closed, entering the info, then closing starparse immediately. Now on re-opening they're all there. Can't get the overlays to behave though,  they need to be added, moved, and resized each time

**Comment by Rash-in** [comment]
`I followed your suggestions, but I'm not sure if it changed anything.`
- If you are able to choose a directory, hit stuff, see numbers. close out app, re-open and not have to choose a log folder again, then it is doing what it needs to to work. (the command just changed the owner on the file permissions so that the app is able to read and write to them.)

Overlays are a different beast. What is your linux distro and desktop environment?

**Comment by blammymatazz** [comment]
I'm on Pop OS with gnome 40.4.0

**Comment by Rash-in** [comment]
Looked into this a bit further. Originally thought it may have been with the interaction with the window decorator but I was wrong.

Now that you are able to write to the starparse.xml file, when you parse with a character in-game, it should save the settings in the starparse.xml file (`<character><popout>`). You shouldn't need to do anything else to get the overlays working as intended.

Try parsing with a character in-game (with your overlays active), then close starparse out and re-open.  I believe that the most you will have to do is set the window to be [always on top](https://github.com/Rash-in/StarParseLinux#6-addendum-overlays-gnome) but it should be positioned in the same place that you had before and at the same size.

Lemme know if that isn't the case.

**Comment by Rash-in** [comment]
I added the steps to modify the permissions on the readme at step 3. Going to consider this as fixed. Lemme know if you still have issues with this and I will re-open.
